### PR TITLE
Use ripgrep for calculating firmware size

### PR DESCRIPTION
**Pull request by soonick**
Hello @technyon , this change might be a little controversial, but I wanted to check if you would be interested.

My comment explains what and why.

If this interests you, I can modify the readme so the note is in a better section.

Regards,

### CODE REVIEW

**Comment by technyon** [comment]
I'm on the fence with this PR. I see it's a good improvement, but on the other hand it's another dependency that could potentially could be problematic. Should we maybe make this optional, so that if ripgrep is detected it uses it as an alternative method to determine firmware size?

**Comment by KSDaemon** [comment]
my 50cents: I agree with @technyon. `ripgrep` is not so popular and probably is not available out of the box on developers machines. So it would be great to auto-detect it and use if it exists or show gentle notice about it in other case. But making it a hard dep — doesn't look great.

**Comment by soonick** [comment]
Sounds fair. I should be able to detect ripgrep and use it if available. I'll update the PR in the next days

**Comment by soonick** [comment]
@technyon , I have made it to ripgrep is only used if available. Please take a look and let me know what you think.

**Comment by technyon** [comment]
Looks good, I've checked building for an ESP32 without ripgrep, no problems at all.

**Comment by technyon** [comment]
I'll have a look into it, never really thought about it actually.

**Pull request merged**
